### ISSUE TITLE
How to disable purchases?

### ISSUE THREAD

**Issue by TheL1ne** [Better-Scenes/RimConnect-mod#29]
Nowhere in the wiki is mentioned how you can disable specific purchases all together. As there are events with a cost of "-1" as default I would assume that a negative input in the cost does disable the event but that is just a guess. It could also give more coins when you try to subtract "-1" from the silver someone has.

So please add somewhere in the wiki how to disable purchases.

**Comment by InfinitySamurai** [comment]
Thanks @TheL1ne, this is one that fell under the carpet. We always intended to build in a more intuitive system to enable/disable purchases, but development at the moment as all but stopped. I'll write some documentation for it now

**Comment by InfinitySamurai** [comment]
Awesome feedback, thank you very much. I've updated the wiki over here including that info along with some other info about the item settings: https://github.com/Better-Scenes/RimConnect-mod/wiki/How-to-use#Store

**Comment by TheL1ne** [comment]
Thanks for the update. Much better now.
