### ISSUE TITLE
ease up on the diseases

### ISSUE THREAD

**Issue by Muramas** [Better-Scenes/RimConnect-mod#30]
I have been trying out rimconnect and it seems to heavily lean towards diseases as the choice for random events and usually gives a choice of three different diseases so there is no option out of it.
In my mind for streaming, diseases is are interesting when they happen once in a while but having rimconnect spawn multiple diseases constantly, it means your colonists are sitting around in bed and nothing much happens for a while until people recover or die due to everyone being sick.

Can you please 
-Mix up the event types more (Re: Good event, bad event, disease)
-Lower diseases spawn chance a bit

**Comment by InfinitySamurai** [comment]
Hey Muramas,

I'm not sure you're in the right mod repo, we don't trigger random events in RimConnect. We allow moderators to create polls of events, and for viewers to purchase items and events. Event purchases are also disabled by default. Are you looking for Twitch Toolkit or Toolkit core?

**Comment by Muramas** [comment]
oh my mistake if it is the wrong mod! I have both of them installed because Rimconnect has a superior buying menu and I thought the events were coming from it for some reason. thanks.
