### ISSUE TITLE
Game disconnected from twitch extension. 

### ISSUE THREAD

**Issue by cleio81** [Better-Scenes/RimConnect-mod#37]
the game has become disconnected from the twitch extension. The extension is stuck authenticating and has no other actions available the mod in game said connected until i tried to disconnect and reconnect. Now it's just stuck at disconnected.  

steps i've tried
restarting the game
uninstalling the extension from twitch
uninstalling the mod from rimworld
reconnecting from the mod setting menu in rimwold

Not sure how to proceed. please help.

**Comment by InfinitySamurai** [comment]
Hey, please drop by our Discord so we can troubleshoot with you. https://discord.gg/HmNA7Sb
My immediate question is, do you have a lot of mods? We're having some trouble with large event lists coming into our server

**Comment by InfinitySamurai** [comment]
Uhm, nevermind, server completely crashed overnight, weird
