### ISSUE TITLE
Feature Request: Loyalty Store Settings Presets

### ISSUE THREAD

**Issue by Rando303** [Better-Scenes/RimConnect-mod#38]
As a user of the mod, I would like to be able to bulk alter the Loyalty Store Settings to preset values to allow for a limited store at the start of a colony, and expanding the store as the colony advances.

The Loyalty Store Settings appear to not be saved locally to the mod XML.  Currently, it is a lot of effort to go through and manually edit the settings within the RimWorld mod settings (maintaining a separate side record of desired settings to edit in one item at a time).  Exposing the XML/JSON that stores the settings could allow saving off and restoring preset values so that work doesn't need repeated on every colony.

**Comment by InfinitySamurai** [comment]
Hi Rando303, 

Unfortunately exposing that information is not as simple as other mods like Twitch Toolkit which completely runs locally. We use a server between between Twitch and your game where we store the data about your items and their cost.

I understand your frustration with changing large numbers of items, but we have no plans to build a solution to enable JSON import/export.
