### ISSUE TITLE
Server Unreachable

### ISSUE THREAD

**Issue by Kuuchuu** [Better-Scenes/RimConnect-mod#54]
~~RimConnect Integration/Extension possibly removed from Twitch? I get a "content unavailable" message when attempting to access the extension page for it,~~ and my game is no longer connecting to the server: "Failed to connect. Is your secret correct?", "HTTP status code: BadRequest", "Unable to Connect to RimConnect server"

EDIT: First part seems to be a Twitch issue. On my extensions page it lists RimConnect, but when I click the name to view the extension page for RimConnect it takes me to the "content unavailable" page, but the extension page url listed on the Steam Workshop description does work properly. Upon closer inspection the Twitch provided link seems to be adding what I believe is a version number to the end of the url, which is not correct. Still investigating server connection issue. Possibly conflict with Prepatcher?

**Comment by Kuuchuu** [comment]
Tried a different computer, same thing
![image](https://github.com/Better-Scenes/RimConnect-mod/assets/20036947/30b68302-73ba-4fde-ab82-fe3f19fa6a4c)

**Comment by Kuuchuu** [comment]
Seems to be working now, unsure what the issue was.

**Comment by rohanrichards** [comment]
Thanks for the info and for closing this off, I dont see any outages so not sure what it was either.
